#if !canImport(ObjectiveC)
import XCTest

extension ProcessTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ProcessTests = [
        ("testByName", testByName),
        ("testByPath", testByPath),
        ("testExitTimeout", testExitTimeout),
        ("testFileChannel", testFileChannel),
        ("testStatus", testStatus),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ProcessTests.__allTests__ProcessTests),
    ]
}
#endif
